# Generated by Django 3.1.7 on 2021-03-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0003_expenseinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseinfo',
            name='user_expense',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_column='Username', default='Required Field', max_length=100),
        ),
    ]
