# Generated by Django 3.1.7 on 2021-03-31 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0004_auto_20210331_0557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterModelTable(
            name='expenseinfo',
            table='Expense Info',
        ),
    ]
