# Generated by Django 3.1.7 on 2021-03-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0005_auto_20210331_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='Username', default='Required Field', max_length=100)),
                ('firstname', models.CharField(db_column='First Name', default='Required Field', max_length=100)),
                ('lastname', models.CharField(db_column='Last Name', default='Required Field', max_length=100)),
                ('email', models.EmailField(db_column='Email', default='Required Field', max_length=30)),
                ('password', models.CharField(db_column='Password', default='Required Field', max_length=30)),
            ],
            options={
                'db_table': 'User Info',
            },
        ),
    ]
