# Generated by Django 3.1.7 on 2021-03-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0007_auto_20210331_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='salary',
            field=models.IntegerField(default='income'),
        ),
    ]
