# Generated by Django 3.1.7 on 2021-03-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0008_users_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
