# Generated by Django 3.1.7 on 2021-03-31 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0009_auto_20210331_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='salary',
        ),
    ]
